#+TITLE:Review Response: Trees in many US cities may indirectly increase atmospheric carbon 
#+AUTHOR: Tedward Erker^*, Philip A. Townsend
#+email: erker@wisc.edu
#+PROPERTY: header-args:R :session *R* :cache no :results output :exports both :tangle yes :eval yes
#+OPTIONS: toc:nil num:nil date:t
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \usepackage{chemformula}
#+LaTeX_HEADER: \RequirePackage{lineno} \def\linenumberfont{\normalfont\small\tt}
#+latex_header: \hypersetup{colorlinks=true,linkcolor=black, citecolor=black, urlcolor=black}
#+latex_header: \usepackage{setspace} \doublespacing
#+LATEX_CLASS_OPTIONS: [12pt]
------------
#+begin_src emacs-lisp :exports none
(setq org-latex-caption-above nil)
#+end_src

#+RESULTS:

* Summary of Changes
- 3's comments about big picture.  My stance should be more
  collaborative.  highlight the complementary nature of my work to the
  modeling approaches.
- I need to show that many papers 


* Response to Reviewer Comments

** Referee: 1 

Review report ERC-100072.pdf

Comments:
1. The results of yours are so strongly dependent on the number of
   heating and cooling degree days and the fuels/technologies utilized
   for electricity and heat production, that it does not make sense
   presenting the results without this information presented first.

   1. I mention this in the 4th paragraph on page 3, lines 44-45.  I
      will add emphasis to this point at the start of the discussion
      section.

2. You should not satisfy with your case results, but look at the
   conditions in which the balance is turned other way round
   (referring to the first comment).

   1. This is what I attempted to do by updating Akbari and Konopacki
      2005 model.  I think that a proper analysis that could
      accurately identify the thresholds in climate and other
      important contributing factors is beyond the scope of this
      paper.  My aim was to present our case results and identify that
      

3. You should discuss the distance issue in the introduction. Now you
   are sort of partially discussing all urban trees, but then
   continuously referring to “shade trees”. You also refer to energy
   need reduction as the primary gain from tree planting programs,
   which points at these shade trees rather than all urban trees.

4. You go deep into the previous studies in the introduction. I
   suggest splitting up the section to a shorter and simpler
   introduction and previous literature gap analysis.

5. Don’t limit your generalizability discussion to just the U.S.

6. I wonder why you don’t mention building types at all in the
   introduction. It is not uniform how the shading effect works with
   buildings of different types, and presumably in cool climates the
   buildings are on average better insulated.

7. Extend the study description from the current one short sentence on
   lines 107-108. Even if the paper follows the style guideline
   placing the methods and data descriptions to the end, you must
   briefly tell to the reader what was done.

8. Please explain better how only north side cover can lead to an
   increase in the need for warming. Shouldn’t tree coverage lead to
   lower heat loss through the north wall?

9. Extend the C storage comparison section with the actual outcome
   numbers and meaning.

10. In the “considering the larger C cycle”, I would find it
    appropriate to notice that hundreds of years of storage can be
    very important in mitigating climate change now and allowing for
    energy system transition to take place.

11. You are making several assumptions yourselves, but don’t discuss
    much this aspect of your study (you point out some weak
    assumptions in previous studies).

** Referee: 2 

COMMENTS TO THE AUTHOR(S) 
- The paper summarizes the results of a statistical analysis. 

- No data or results are shown and the reader has to rely on the authors for their conclusions. 

- The physics of the claim that trees increase CO2 emission is not explained and modeled. 

- One cannot understand the basis of the conclusions with supporting data. 

** Referee: 3 

COMMENTS TO THE AUTHOR(S) [See also ER_system_appendPDF_proof_hi.pdf] 
Nice paper. Comments are on the attachment. The paper needs some
clarification of methods and a little more discussion, but overall it
is a very good paper. My main issues relate to using the Akbari and
Konopacki results to extrapolate to the nation; how you were able to
separate shade and wind effects; and the discussion should delve more
into why these patterns occurred. 


One item you might want to expand on in the discussion is that though
your results contradict most, but not all, results for northern
climates, they do not necessarily negate the findings of past
studies. It opens an interesting question for more research
though. You basically have an analysis of one city (the national
analysis is questionable). Other studies used energy simulations that
had limitations, but your results do not necessarily render previous
studies as incorrect. Past studies have found these negative winter
effects, but maybe not to your degree. Your work is interesting and
opens questions for further research, but is not conclusive
nationally. Your work compares one modeling approach results with
other modeling approach results; and both have limitations.  Bottom
line is that trees in more northern climates could increase carbon
emissions and more research is needed as to how much and why. 

Comments on pdf (lines are from original submission):
- Title. Maybe add "due to altered energy use" in the title as your findings
  indicate that if sequestration is included, carbon has a net
  positive sequestration. 
- line 126. This difference also has to do with the ratio of emission to the
  fuel source. If one changes the fuel, the C emissions will change
  but the energy effect will stay the same.
- line 142. "So the tree is a net reduction in C? Maybe report the net effect of both to be clear"
- line 147. "How do you know shading was the driving factor, vs
  transpiration or wind? Also how does comparing winter vs summer
  effects lead to the conclusion for winter effects?"
- line 153. "Good"
- line 161. "Why might this be?"
- line 178. "Although I agree with this conclusion, I find it somewhat
  contradictory that the basis for this work in the introduction is
  the limitations of past studies, but you use these past studies to
  extrapolate nationwide. Why not just use your findings to make this
  point - in heating dominated areas, tree can increase C carbon
  emissions. Extrapolating the Akbari data is suspect due to their
  assumptions on tree cover. Your data are from actual tree
  distributions. I would drop this national analysis as it is already
  known that trees can increase winter energy use. Use past studies to
  back your findings. Also note that fuel mix is important in carbon
  emissions as is tree location."
- line 184. "McPherson and Simpson methods are used in iTree, but it is not the model."
- line 185. "Northern"
- line 188. "How did you separate out shade effects?"
- line 192. "I am confused as to how you can separate or did separate wind from shading effects"
- line 218. "It might good to note that this information can also be
  used to improve planting designs, particularly in colder climates to
  reduce energy use and carbon emissions"
- line 235. "Good"
- line 267. "Again, I do not see how you conclude this difference between wind and shade."
- line 309. "What is the accuracy of the tree cover data?"
- line 327. "What is the accuracy of the building cover data?"
- line 374. "This is confusing text as to what was actually done. Are
  you interpolating Akbari and Konopacki results to this area with 77%
  of the population? If so, how to do you account for varying tree
  cover across the nation? The Akbari paper uses 4, 8 and 10 trees
  around the building for their assumption of tree cover. If you are
  arguing that these previous models have limitations based on their
  assumptions, why use these models for national extrapolation. I may
  be misreading these methods, but either way, these methods needs to
  be clarified."

Letter reference: DSMa01

